Minishop\ShopBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        brand:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        price:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
