minishop_shop_category:
    resource: "@MinishopShopBundle/Resources/config/routing/category.yml"
    prefix:   /category

minishop_shop_product:
    resource: "@MinishopShopBundle/Resources/config/routing/product.yml"
    prefix:   /

#minishop_shop_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: MinishopShopBundle:Default:index }
